version: "3.8"
services:
  web-2:
    build: ./web
    volumes:
      - ./web/html/index.php:/var/www/html/index.php
    ports:
      - 80:80
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: MyDB
      MYSQL_USER: lucgryy
      MYSQL_PASSWORD: 123456
